name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the event-aggregator Docker image
        run: docker build .
      - name: Build the mock-server Docker image
        run: docker build ./mock-server/.
